install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("here")
install.packages(c("sysfonts", "jsonlite", "curl", "showtext"))
install.packages("devtools")
devtools::install_github("thomasp85/gganimate")
