if (!dir.exists(here::here("images"))) dir.create(here::here("images"))
png_path <- here::here("images", "static", "png")
svg_path <- here::here("images", "static", "svg")
if (!dir.exists(png_path)) dir.create(png_path, recursive = TRUE)
if (!dir.exists(svg_path)) dir.create(svg_path, recursive = TRUE)
